try {
  raise Error("example");
  assert(false);
} catch {
  assert(true);
}