  try {
    raise Error("test");
  } catch e: 10 {
  }