try {
  raise Error("raise");
  assert(false);
} catch {
  try {
    raise Error("raise");
    assert(false);
  } catch {
    assert(true);
  }
}