fn error() {
  return nil + false;
}

error.call();