let error1 = Error("broken");
let error2 = Error("broken again", error1);

assertEq(error1.message, "broken");
assertEq(error1.inner, nil);
assertEq(error1.backTrace.cls(), List);
assertEq(error1.backTrace.len(), 0);

assertEq(error2.message, "broken again");
assertEq(error2.inner, error1);
assertEq(error1.backTrace.len(), 0);
